version: '3.8'
services:
  dt_dev_nginx:
    container_name: dt_dev_nginx
    image: dt_dev/nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - dt_dev_app
    networks:
      - dt_dev

  dt_dev_app:
    image: dt_dev/app
    container_name: dt_dev_app
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - dt_dev_pgsql
      - dt_dev_redis
    networks:
      - dt_dev

  dt_dev_worker:
    container_name: dt_dev_worker
    image: dt_dev/worker
    build:
      context: .
      dockerfile: ./.docker/worker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - dt_dev_pgsql
      - dt_dev_redis
    networks:
      - dt_dev

  dt_dev_pgsql:
    container_name: dt_dev_pgsql
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - dt_dev_postgres:/var/lib/postgresql/data
    networks:
      - dt_dev
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  dt_dev_redis:
    container_name: dt_dev_redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - dt_dev_redis:/data
    networks:
      - dt_dev
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  dt_dev_adminer:
    container_name: dt_dev_adminer
    image: adminer:latest
    ports:
      - '${FORWARD_ADMINER_PORT:-8089}:8080'
    depends_on:
      - dt_dev_pgsql
    networks:
      - dt_dev

networks:
  dt_dev:
    driver: bridge

volumes:
  dt_dev_postgres:
    driver: local
  dt_dev_redis:
    driver: local
